version: '3'
services:
  db:
    depends_on:
      - web
    build:
      context: ./docker/db
    volumes:
      - ./webroot/docker/db/db_data:/var/lib/mysql
  web:
    build:
      context: ./docker/web
    ports:
      - "3000:80"
    volumes:
      - ./webroot:/var/www/html
  # wordpress:
  #   depends_on:
  #     - db
  #   build:
  #     context: ./docker/wordpress
    